car_type: nina
protocols:
  '10':
    id: '10'
    name: remote_indicator_request
    protocol_type: control
    sender: GatewayPC
    vars:
    - bit: 10
      is_signed_var: false
      len: 2
      name: remote_status_light_blink_rate_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 8
      is_signed_var: false
      len: 2
      name: remote_status_light_color_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 7
      is_signed_var: false
      len: 1
      name: remote_horn_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 6
      is_signed_var: false
      len: 1
      name: remote_light_brake_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 5
      is_signed_var: false
      len: 1
      name: remote_blink_left_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 4
      is_signed_var: false
      len: 1
      name: remote_blink_right_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 3
      is_signed_var: false
      len: 1
      name: remote_brights_on_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 2
      is_signed_var: false
      len: 1
      name: remote_light_reverse_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 1
      is_signed_var: false
      len: 1
      name: remote_lights_turn_left_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 0
      is_signed_var: false
      len: 1
      name: remote_lights_turn_right_req
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
  '11':
    id: '11'
    name: remote_drive_request
    protocol_type: control
    sender: GatewayPC
    vars:
    - bit: 16
      is_signed_var: true
      len: 16
      name: remote_steering_angle_req
      offset: 0.0
      order: intel
      physical_range: '[-327.68|327.67]'
      physical_unit: ''
      precision: 0.01
      type: double
    - bit: 0
      is_signed_var: true
      len: 16
      name: remote_velocity_req
      offset: 0.0
      order: intel
      physical_range: '[-32.768|32.767]'
      physical_unit: ''
      precision: 0.001
      type: double
  '2':
    id: '2'
    name: general_vehicle_status
    protocol_type: report
    sender: TTC
    vars:
    - bit: 39
      is_signed_var: false
      len: 1
      name: signal12_switch
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 56
      is_signed_var: false
      len: 1
      name: request_zero_throttle
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 57
      is_signed_var: false
      len: 1
      name: request_brake
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 35
      is_signed_var: false
      len: 1
      name: signal_brights_on
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 32
      is_signed_var: false
      len: 1
      name: signal_right_turn
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 33
      is_signed_var: false
      len: 1
      name: signal_left_turn
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 38
      is_signed_var: false
      len: 1
      name: signal_horn
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 37
      is_signed_var: false
      len: 1
      name: signal_hazard_lights
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 36
      is_signed_var: false
      len: 1
      name: signal_fog_lights
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 34
      is_signed_var: false
      len: 1
      name: signal_direction_reverse
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 30
      is_signed_var: false
      len: 1
      name: global_man_sig_mag_brake
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 31
      is_signed_var: false
      len: 1
      name: global_curtis_sig_mag_brake
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 29
      is_signed_var: false
      len: 1
      name: signal_brake_switch
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 28
      is_signed_var: false
      len: 1
      name: signal_seat_switch
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 3
      is_signed_var: false
      len: 1
      name: e_stop_status
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 16
      is_signed_var: false
      len: 12
      name: enabled_applications
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 4
      is_signed_var: false
      len: 4
      name: selected_application
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 8
      is_signed_var: false
      len: 4
      name: selected_op_mode
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 12
      is_signed_var: false
      len: 4
      name: active_op_mode
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 1
      name: button_blue
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 1
      is_signed_var: false
      len: 1
      name: button_yellow
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
    - bit: 2
      is_signed_var: false
      len: 1
      name: button_green
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: bool
  '3':
    id: '3'
    name: stearing_and_speed
    protocol_type: report
    sender: TTC
    vars:
    - bit: 40
      is_signed_var: true
      len: 8
      name: vehicle_velocity_requested
      offset: 0.0
      order: intel
      physical_range: '[-12.8|12.7]'
      physical_unit: ''
      precision: 0.1
      type: double
    - bit: 16
      is_signed_var: true
      len: 16
      name: steering_position_requested
      offset: 0.0
      order: intel
      physical_range: '[-163.84|163.835]'
      physical_unit: ''
      precision: 0.005
      type: double
    - bit: 32
      is_signed_var: true
      len: 8
      name: vehicle_velocity_measured
      offset: 0.0
      order: intel
      physical_range: '[-12.8|12.7]'
      physical_unit: ''
      precision: 0.1
      type: double
    - bit: 0
      is_signed_var: true
      len: 16
      name: steering_position_measured
      offset: 0.0
      order: intel
      physical_range: '[-163.84|163.835]'
      physical_unit: ''
      precision: 0.005
      type: double
  '30':
    id: '30'
    name: u_s_sensor_front
    protocol_type: report
    sender: TTC
    vars:
    - bit: 48
      is_signed_var: false
      len: 16
      name: u_s_sensor4
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 32
      is_signed_var: false
      len: 16
      name: u_s_sensor3
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 16
      is_signed_var: false
      len: 16
      name: u_s_sensor2
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 16
      name: u_s_sensor1
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '31':
    id: '31'
    name: u_s_sensor_rear
    protocol_type: report
    sender: TTC
    vars:
    - bit: 48
      is_signed_var: false
      len: 16
      name: u_s_sensor8
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 32
      is_signed_var: false
      len: 16
      name: u_s_sensor7
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 16
      is_signed_var: false
      len: 16
      name: u_s_sensor6
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 16
      name: u_s_sensor5
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '40':
    id: '40'
    name: raw_signal_throttle
    protocol_type: report
    sender: TTC
    vars:
    - bit: 32
      is_signed_var: false
      len: 32
      name: uint32_signal_throttle_b
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 32
      name: uint32_signal_throttle_a
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '41':
    id: '41'
    name: raw_signal_break
    protocol_type: report
    sender: TTC
    vars:
    - bit: 32
      is_signed_var: false
      len: 32
      name: uint32_signal_brake_b
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 32
      name: uint32_signal_brake_a
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '42':
    id: '42'
    name: raw_signal_steering_force
    protocol_type: report
    sender: TTC
    vars:
    - bit: 32
      is_signed_var: false
      len: 32
      name: uint32_signal_steering_force_b
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 32
      name: uint32_signal_steering_force_a
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '43':
    id: '43'
    name: raw_signal_steering_position
    protocol_type: report
    sender: TTC
    vars:
    - bit: 16
      is_signed_var: false
      len: 16
      name: uint16_encoder_raw_value_b
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 16
      name: uint16_encoder_raw_value_a
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '44':
    id: '44'
    name: raw_signal_steering_velocity_cmd
    protocol_type: report
    sender: TTC
    vars:
    - bit: 0
      is_signed_var: true
      len: 16
      name: int16_steering_velocity_cmd
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
  '45':
    id: '45'
    name: raw_signal_steering_velocity
    protocol_type: report
    sender: TTC
    vars:
    - bit: 0
      is_signed_var: true
      len: 16
      name: int16_steering_velocity
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 0.1
      type: double
  '46':
    id: '46'
    name: raw_signal_vehicle_speed
    protocol_type: report
    sender: TTC
    vars:
    - bit: 0
      is_signed_var: false
      len: 8
      name: uint8_vehicle_speed
      offset: 0.0
      order: intel
      physical_range: '[0|25.5]'
      physical_unit: ''
      precision: 0.1
      type: double
  '47':
    id: '47'
    name: raw_signal_throttle_poti_cmd
    protocol_type: report
    sender: TTC
    vars:
    - bit: 0
      is_signed_var: false
      len: 16
      name: uint16_poti_throttle_cmd
      offset: 0.0
      order: intel
      physical_range: '[0|65535]'
      physical_unit: ''
      precision: 1.0
      type: int
  '48':
    id: '48'
    name: scaled_signals
    protocol_type: report
    sender: TTC
    vars:
    - bit: 24
      is_signed_var: false
      len: 8
      name: throttle_signal
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 40
      is_signed_var: true
      len: 8
      name: steering_motor_speed_cmd
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 32
      is_signed_var: false
      len: 8
      name: curtis_speed_cmd
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 16
      is_signed_var: true
      len: 8
      name: steering_torque_signal
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 8
      is_signed_var: true
      len: 8
      name: steering_velocity_signal
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
    - bit: 0
      is_signed_var: false
      len: 8
      name: brake_signal
      offset: 0.0
      order: intel
      physical_range: '[0|0]'
      physical_unit: ''
      precision: 1.0
      type: int
